server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://MYSQL1002.site4now.net:3306/db_ab758f_bao?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
    username: ab758f_bao
    password: Giabao123@  # Thay thế bằng mật khẩu thực tế của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: SpringBootJPAHikariCP
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate  # Đổi từ update sang validate để tránh lỗi khi connect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC