server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://dpg-d0qig7be5dus739jie60-a.oregon-postgres.render.com/ql_khoahocsql"
    username: ql_khoahocsql_user
    password: 8fZYz2xi0R9rppu7UQpoBbBfawhaUzRC
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: SpringBootJPAHikariCP
      connection-test-query: SELECT 1
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true